

print "Problem 2"
print "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:"
print "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..."
print "\n"

no = int(raw_input("Enter a no till which we need to generate Fibonacci series starting from 1 : "))

curr = 1
prev = 0
fibbo = 1
sum=0

while True:
	fibbo = prev+curr
	prev = curr
	curr = fibbo
	# checking if fibbonaci no is less than the no passed by user and even
	if fibbo < no and fibbo%2==0:
		sum=sum+fibbo
		
	elif fibbo>no:
		break	

print sum

# Atul Singh
# www.datagenx.net



